spring:
  application:
    name: ClinicaFacilSaude
  profiles:
    active: dev

server:
  error:
    include-stacktrace: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true